effi/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('website.urls')),
    url(r'^admin/', admin.site.urls),
]

website/urls.py
from django.conf.urls import url

from . import views

app_name = 'website'

urlpatterns = [
	#/music/
    url(r'^$', views.MainView.as_view(), name='main'),
    url(r'^team/$', views.TeamView.as_view(), name='team'),
    url(r'^gallery/$', views.GalleryView.as_view(), name='gallery'),
    url(r'^sopnsors/$', views.SponsView.as_view(), name='sponsors'),
    url(r'^contact/$', views.contact, name='contact'),

]

website/models.py
from django.db import models

# Create your models here.
class Response(models.Model):
    name = models.CharField(max_length=100)
    email = models.CharField(max_length=200)
    message =models.CharField(max_length=1000)

    def __str__(self):
        return self.name

website/forms.py
from django import forms

# our new form
class ContactForm(forms.Form):
    Name = forms.CharField(required=True)
    Email = forms.EmailField(required=True)
    Message = forms.CharField(
        required=True,
        widget=forms.Textarea
    )

website/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
from django.views.generic import TemplateView
from website.forms import ContactForm
from django.core.mail import EmailMessage
from django.shortcuts import redirect
from django.template import Context
from django.template.loader import get_template
from .models import Response


# Create your views here.
class MainView(TemplateView):
    template_name = "website/main.html"
class TeamView(TemplateView):
    template_name = "website/team.html"

class GalleryView(TemplateView):
    template_name = "website/gallery.html"
class SponsView(TemplateView):
    template_name = "website/sponsors.html"
class ContactView(TemplateView):
    template_name = "website/contact.html"
def contact(request):
    form_class = ContactForm

    if request.method == 'POST':
        form = form_class(data=request.POST)

        if form.is_valid():
            contact_name = request.POST.get(
                'Name'
                , '')
            contact_email = request.POST.get(
                'Email'
                , '')
            form_content = request.POST.get('Message', '')

            # Email the profile with the
            # contact information
            template = get_template('contact_template.txt')
            context = Context({
            'Name': contact_name,
            'Email': contact_email,
            'Message': form_content,
            })
            content = template.render(context)

            a =Response()
            a.name=contact_name
            a.email=contact_email
            a.message=form_content
            a.save()


            email = EmailMessage(
            "New contact form submission",
            content,
            "Your website" + '',
            ['youremail@gmail.com'],
            headers={'Reply-To': contact_email}
            )
            email.send()
            return redirect('website:contact')

    return render(request, 'website/contact.html',{'form':form_class})

website/templates/website/contact.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Contact Us</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" type="text/css">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'website/css/contact-style.css' %}">

    <script>
        $(document).ready(function () {
           $("#logo").hover(function () {
            $(this).attr('src',"{% static 'website/img/logo.png' %}");
           },function () {
            $(this).attr('src',"{% static 'website/img/logo2.png' %}");
               });
        });

    </script>

</head>
<body>
	<nav class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'website:main' %}"><img id="logo" src="{% static 'website/img/logo2.png' %}"></a>
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#Nav">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>
        <div class="collapse navbar-collapse" id="Nav">
            <ul class="nav navbar-nav navbar-right text-center">
                <li><a class="list" href="{% url 'website:main' %}#about">ABOUT</a></li>
				<li><a class="list" href="{% url 'website:team' %}">TEAM</a></li>
                <li><a class="list" href="{% url 'website:gallery' %}">GALLERY</a></li>
                <li><a class="list" href="{% url 'website:sponsors' %}">SPONSORS</a></li>
                <li><a class="list" href="">CONTACT</a></li>
            </ul>
        </div>
            </div>

    </nav>
    <div class="container">
        <div class="row">
            <div class="col-sm-6">
            <div class="box">
                <div class="clist">
		<h1 class="text-center">Contacts</h1>
		<ul style="list-style-type:none">


		<li> <span class="marker"><i class="fa fa-envelope fa-lg"></i></span> thunderbolt5.0nitw@gmail.com </li>
		<li> <span class="marker"><i class="fa fa-phone fa-lg"></i></span> +(91)8790518974 (K. Urvidhar Reddy) </li>
		<li> <span class="marker"><i class="fa fa-phone fa-lg"></i></span> +(91) 8446263263 (Sujan Karegoudar) </li>
		<li> <span class="marker"><i class="fa fa-phone fa-lg"></i></span> +(91) 9440943793 (Rishi Kapadia) </li>
		<li> <span class="marker"><i class="fa fa-phone fa-lg"></i></span> +(91) 8560831377 (Utsav Solanki)</li>
		</ul>
<pre>
<span class="mark"><i class="fa fa-map-marker fa-lg"></i></span>Team Thunderbolt 5.0
   Mechanical Department
​   NIT Warangal
   Warangal, Telengana-506004
</pre>
    </div>

            </div>
            </div>
            <div class="col-sm-6">
            <div class="box">
            <div class="bod">
        <h2 class="text-center">Send Email</h2>
    <form role="form" action="" method="post">

        {% csrf_token %}

        {% for field in form %}
	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			<span class="text-danger small">{{ field.errors }}</span>
		</div>

		<label class="control-label col-sm-2">{{ field.label_tag }}</label>
		<div class="col-sm-10">{{ field }} </div>
	</div>
        {%  endfor %}
<div class="col-sm-offset-2 col-sm-10">
        <button class="btn btn-success"type="submit">Submit</button>
</div>
    </form>
    </div>
            </div>
            </div>
        </div>
    </div>


</body>
</html>

website/templates/website/main.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>Thunderbolt 5.0</title>   
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" type="text/css">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'website/css/style.css' %}">
	<!--script type="text/javascript" src="{% static 'website/javascript/script.js' %}"></script-->
	
	<script>
$(document).ready(function(){
$('.bolt').css("border-radius","125px");
	
  
  $(".navbar a").on('click', function(event) {

  if (this.hash !== "") {

    event.preventDefault();

    var hash = this.hash;

   $('html, body').animate({
      scrollTop: $(hash).offset().top
    }, 900, function(){

      window.location.hash = hash;
      });
    }
  });
  $("#logo").hover(function () {
            $(this).attr('src',"{% static 'website/img/logo.png' %}");
           },function () {
            $(this).attr('src',"{% static 'website/img/logo2.png' %}");
               });
  $(".fb").hover(function(){
        $(this).addClass("pul");
        }, function(){
        $(this).removeClass("pul");
    });
});
</script>
</head>
    
<body id="myPage" data-spy="scroll" data-target=".navbar" data-offset="60">

    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="#"><img id="logo" src="{% static 'website/img/logo2.png' %}"></a>
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#Nav">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>      
        <div class="collapse navbar-collapse" id="Nav">
            <ul class="nav navbar-nav navbar-right text-center">
                <li><a class="list" href="#about">ABOUT</a></li>
				<li><a class="list" href="{% url 'website:team' %}">TEAM</a></li>
                <li><a class="list" href="{% url 'website:gallery' %}">GALLERY</a></li>
                <li><a class="list" href="{% url 'website:sponsors' %}">SPONSORS</a></li>
                <li><a class="list" href="{% url 'website:contact' %}">CONTACT</a></li>
            </ul>
        </div>
            </div>
        
    </nav>
    
        <div class="container-fluid logo text-center">
            
        
            <div class="line l1">
            </div>
            

            <div class="boltcov text-center">
            <div class="bolt">
                <img src="{% static 'website/img/logo_hover.png' %}" style="width: 200px" alt="cap" />
            </div>
            </div>
                <div class="thu">
                <strong> THUNDERBOLT 5.0</strong>
                    </div>
                 
			<div>
                <a href="https://www.facebook.com/TeamThunderboltnitw/" target="_blank"><span class="fb"><i class="fa fa-facebook"></i></span></a>
            </div>

                
        </div>
            
        
    <div class="container-fluid about" id="about">
        <div class="container">
		<h1 class="text-center heading">About Thunderbolt 5.0</h1><br />
		<p class="para">
​​​		Team THUNDERBOLT 5.0 comprises of 10 budding engineers passionate about designing,
		manufacturing, analysing and marketing of an electric hybrid recumbent trike.</p>
		
		<br />
		
		<h1 class="text-center heading">About NITW</h1><br />
		<p class="para">
National Institute of Technology, Warangal (shortened to NIT WARANGAL or NITW) is a premier federally funded technical institute in India. 
It is one of the Institutes of National Importance (INI) established by the government of India,
 awarding bachelors, masters and doctoral degrees in engineering, technology, basic sciences and management.
		</p>
		
		<h1 class="text-center heading">About Event</h1><br />
		<p class="para">
			SAE NIS EFFICYCLE is an Intercollegiate design competition for the undergraduate and 
			graduate engineering students where team of 6-10 students have to design and 
			fabricate an energy efficient Hybrid human powered three wheeled electric vehicle.
			<br />
			The fabricated Efficycle is judged by eminent professionals from the industry on the basis of design,
			build quality, costing and marketability. The vehicles have to undergo technical Inspection followed by dynamic events- Acceleration, utility, maneuverability 
			& gradient test. The two hour final endurance race tests the durability of the vehicle.
		</p>
		</div>
    </div>
	
	
    
</body>

</html>

website/templates/website/sponsors.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>Sponsors</title>   
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" type="text/css">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'website/css/spon-style.css' %}">
<script>
        $(document).ready(function () {
           $("#logo").hover(function () {
            $(this).attr('src',"{% static 'website/img/logo.png' %}");
           },function () {
            $(this).attr('src',"{% static 'website/img/logo2.png' %}");
               });
        });

    </script>

</head>
<body>
	<nav class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'website:main' %}"><img id="logo" src="{% static 'website/img/logo2.png' %}"></a>
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#Nav">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>      
        <div class="collapse navbar-collapse" id="Nav">
            <ul class="nav navbar-nav navbar-right text-center">
                <li><a class="list" href="{% url 'website:main' %}#about">ABOUT</a></li>
				<li><a class="list" href="{% url 'website:team' %}">TEAM</a></li>
                <li><a class="list" href="{% url 'website:gallery' %}">GALLERY</a></li>
                <li class="active"><a class="list" href="">SPONSORS</a></li>
                <li><a class="list" href="{% url 'website:contact' %}">CONTACT</a></li>
            </ul>
        </div>
            </div>
        
    </nav>
	
	
	<h1 class="title" style="width: 100%; text-align: center">OUR SPONSORS</h1>
	
	<div class="col-md-12 text-center tagline">
                        Contribute to be a part of Innovation.
                    </div>
	
	<div class="row text-center">
        <a style="text-decoration:none" href="{% url 'website:contact' %}"><span  class="spon">Sponsor Us</span></a>
                </div>
</body>
</html>

website/templates/website/team.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>The Team</title>   
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" type="text/css">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    
	
	<link rel="stylesheet" type="text/css" href="{% static 'website/css/team-style.css' %}">
	<script>
   $(document).ready(function(){

	$(document).on('scroll', function (e) {
	
		if($(document).scrollTop()>800)
		{$('.navbar').css('opacity', 1);
		$('.navbar').css('background-color', '#ee7230');
		}
		else
		{$('.navbar').css('opacity', 0.5);
		$('.navbar').css('background-color', '#000000');
		}
		});
	
	$(window).scroll(function() {
	  $(".slideanim").each(function(){
		var pos = $(this).offset().top;

		var winTop = $(window).scrollTop();
		if (pos < winTop + 600) {
		  $(this).addClass("slide");
		}
	  });
	});
	
	$('.parallax').parallax();
  });
  
  
  
  </script>
    <script>
        $(document).ready(function () {

           $("#logo").hover(function () {
               if($(document).scrollTop()>800){
            $(this).attr('src',"{% static 'website/img/logo.png' %}");}
           },function () {
            $(this).attr('src',"{% static 'website/img/logo2.png' %}");
               })
        });

    </script>
</head>
<body>

	<nav class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'website:main' %}"><img id="logo" src="{% static 'website/img/logo2.png' %}"></a>
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#Nav">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>      
        <div class="collapse navbar-collapse" id="Nav">
            <ul class="nav navbar-nav navbar-right text-center">
                <li><a class="list" href="{% url 'website:main' %}#about">ABOUT</a></li>
				<li class="active"><a class="list" href="#">TEAM</a></li>
                <li><a class="list" href="{% url 'website:gallery' %}">GALLERY</a></li>
                <li><a class="list" href="{% url 'website:sponsors' %}">SPONSORS</a></li>
                <li><a class="list" href="{% url 'website:contact' %}">CONTACT</a></li>
            </ul>
        </div>
            </div>
        
    </nav>
		
	<div class="parallax-container">
		<div class="parallax"><img class="img img-responsive"src="{% static 'website/img/team.jpg' %}"></div>
	</div>
    <div class=" header text-center">
    <p>THE TEAM</p>
    </div>
    <div class="line center-block"></div>
    <br><br><br><br>
	<div class="container-fluid text-center">
    <div class="row slideanim">
		<div class="grid">
		<div class="cont center-block">
        <figure class="cap">
			<div><img src="{% static 'website/img/urvidar.jpg' %}" alt="cap" /></div>
			<figcaption>
                <div class="ver">
				<h3>K. Urvidhar Reddy (Captain)</h3>
                <br/>
				<p>Design, Documentation, Sponsorship

				</p>
                </div>
			</figcaption>
		</figure>
		</div>
		</div>
		<div class="grid">
		<figure class="vcap">
		<div>
			<img src="{% static 'website/img/vcap.jpg' %}" alt="vcap" /></div>
			<figcaption>
                <div class="ver">
				<h3>Sujan Karegoudar (Vice-Captain)</h3>
                <br/>
				<p>
				Steering, Suspension, Documentation
				</p>
                    </div>
			</figcaption>
		</figure>
		</div>
	</div>
	<div class="teamrow slideanim">
		<div class="tgrid">
        <figure class="team">
			<img src="{% static 'website/img/rishi.jpg' %}" alt="cap" />
			<figcaption>
				<h3 class="title">Rishi Kapadia</h3>
				<p>
				Analysis, Design, Suspension
				</p>
			</figcaption>
		</figure>
		</div>
		<div class="tgrid">
		<figure class="team">
			<img src="{% static 'website/img/vallaba.jpg' %}" alt="vcap" />
			<figcaption>
				<h3>Durba Ganesha Srivallabha</h3>
                <p>
                    Design, Analysis
                </p>
			</figcaption>
		</figure>
		</div>
		<div class="tgrid">
        <figure class="team">
			<img src="{% static 'website/img/tushar.jpg' %}" alt="cap" />
			<figcaption>
				<h3>Tushar Lakhe</h3>
                <p>Suspension, Steering</p>
			</figcaption>
		</figure>
		</div>

    </div>
	<div class="teamrow slideanim">
        <div class="tgrid">
		<figure class="team">
			<img src="{% static 'website/img/guy4.jpg' %}" alt="vcap" />
			<figcaption>
				<h3>Nikhil Birajdar</h3>
                <p>
                    Brakes, Power Transmission
                </p>
			</figcaption>
		</figure>
		</div>
		<div class="tgrid">
        <figure class="team">
			<img src="{% static 'website/img/sourabh.jpg' %}" alt="cap" />
			<figcaption>
				<h3>Saurabh Belgaonkar</h3>
                <p>
                    Power Transmission, Steering
                </p>
			</figcaption>
		</figure>
		</div>
		<div class="tgrid">
		<figure class="team">
			<img src="{% static 'website/img/guy5.jpg' %}" alt="vcap" />
			<figcaption>
				<h3>Akshay Matra</h3>
				<p>
				Power Transmission, Braking
				</p>
			</figcaption>
		</figure>
		</div>

    </div>
    <div class="teamrow slideanim">
        <div class="tgrid">
        <figure class="team">
			<img src="{% static 'website/img/shourya.jpg' %}" alt="cap" />
			<figcaption>
				<h3>Shourya Singh</h3>
                <p>
                    Electrical, Electronics, Sponshorship
                </p>
			</figcaption>
		</figure>
		</div>
		<div class="tgrid">
		<figure class="team">
			<img src="{% static 'website/img/utsav.jpg' %}" alt="vcap" />
			<figcaption>
				<h3>Utsav Solanki</h3>
                <p>
                    Electrical, Power transmission
                </p>
			</figcaption>
		</figure>
		</div>
    </div>
        </div>
    <div class="container-fluid text-center">
	<div class="text-center vol"><h2>VOLUNTEERS</h2></div>
	<br/>
	<br />
	<div class=" row volrow slideanim">
		<div class="vgrid">
        <figure class="team">
			<img src="{% static 'website/img/guy2.jpg' %}" alt="cap" />
			<figcaption>
				<h3>Abhishek Patel</h3>
                <p>Braking</p>
			</figcaption>
		</figure>
		</div>
		<div class="vgrid">
		<figure class="team">
			<img src="{% static 'website/img/guy3.jpg' %}" alt="vcap" />
			<figcaption>
				<h3>Sagar Dabherao</h3>
                <p>
                    Electronics
                </p>
			</figcaption>
		</figure>
		</div>
		<div class="vgrid">
        <figure class="team">
			<img src="{% static 'website/img/asitosgh.jpg' %}" alt="cap" />
			<figcaption>
				<h3>Ashutosh Nagayach</h3>
                <p>
                    Power Transmission
                </p>
			</figcaption>
		</figure>
		</div>
		<div class="vgrid">
		<figure class="team">
			<img src="{% static 'website/img/bangalore.jpg' %}" alt="vcap" />
			<figcaption>
				<h3>Shreyas</h3>
                <p>
                    Suspension
                </p>
			</figcaption>
		</figure>
		</div>

    </div>
    </div>
	
	<div class="bottom"></div>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.0/js/materialize.min.js"></script>
</body>
</html>